### ISSUE TITLE
Is this different in results than lodash.merge?

### ISSUE THREAD

**Issue by ghost** [schnittstabil/merge-options#1]

**Comment by schnittstabil** [comment]
Of course, there are many differences in results, however the main substantive differences are _simplicity_ and _specialization_. `merge-options` is completely dedicated to merge configuration objects (_option objects_), whereas `_.merge` tries to be usable in a more general way.

Thus `_.merge` is rather complex (875 lines of code, atm), in contrast to `merge-options` (104 loc), and returns occasionally surprising results, e.g.:

``` js
const _merge = require('lodash.merge');
const buff = Buffer('foo');
buff.bar = 'bar';

const opts = _merge({}, {foo: buff});
//=> opts.foo.bar === undefined
```

A few more differences, making `_.merge` IMO unsuitable for merging configuration objects:

### Symbol handling

``` js
const CALL_API = Symbol('api');
const opts = _merge({
    [CALL_API]: 0
}, {
    [CALL_API]: 42
});
//=> opts[CALL_API] === 0
```

### Argument mutations

`_.merge` mutates not only the first argument (which is documented), but also subsequent arguments:

``` js
class Car {
}

const car = new Car();
car.wheels = 4;

_merge({}, {vehicle: car}, {vehicle: {wheels: 42}});
//=> car.wheels === 42
```

However, sometimes it does not:

``` js
const car = new Buffer('car');
car.wheels = 4;

_merge({}, {vehicle: car}, {vehicle: {wheels: 42}});
//=> car.wheels === 4
```
