### ISSUE TITLE
TypeScript is not supported

### ISSUE THREAD

**Issue by Androz2091** [schnittstabil/merge-options#22]
Hello,
I'd like to use this package with TypeScript, but it's actually impossible, because there isn't any `.d.ts` file... It would be nice to add them!

**Comment by schnittstabil** [comment]
I'm sorry, but it works fine for me:
```typescript
import * as mergeOptions from "merge-options";

console.log(mergeOptions({foo: 0}, {bar: 1}, {baz: 2}, {bar: 3}));
// => { foo: 0, bar: 3, baz: 2 }
```

**Comment by Androz2091** [comment]
Not for me @schnittstabil... TS needs a type declaration file

**Comment by schnittstabil** [comment]
The above code snippet is pure TS and I've compiled it with TypeScript 3.9.3 without any problems.
Can you provide a compile exception or similar?

**Comment by leandro-manifesto** [comment]
I tested with TypeScript 3.9.6 and the compilation does fails when strict mode is enabled.

**Comment by schnittstabil** [comment]
@leandro-manifesto Thanks for clarifying. 

:tada: `merge-options@3.0.1` introduces basic support for ESM and TS :tada:

```ts
import mergeOptions from 'merge-options'; // <-- NB this change

console.log(mergeOptions({foo: 0}, {bar: 1}, {baz: 2}, {bar: 3}));
// => { foo: 0, bar: 3, baz: 2 }
```
