### ISSUE TITLE
node 12 support?

### ISSUE THREAD

**Issue by achingbrain** [schnittstabil/merge-options#23]
v3 of this module refactored to use esm modules and set the engines field to require node >= 14, yet this module is published transpiled to common js so does run on node 12 at least.

If a user has [engine-strict = true](https://docs.npmjs.com/misc/config#engine-strict) or is running yarn, it'll fail to install on node 12 even though it will run.

Can the engines field be relaxed?  Node 12 is active LTS for another few months and maintenance LTS until spring 2022 so dropping support seems premature.

Refs: https://github.com/ipfs/js-ipfs/issues/3270

**Comment by schnittstabil** [comment]
@achingbrain thanks contributing, fixed at 3.0.2

**Comment by schnittstabil** [comment]
BTW, this module is not transpiled, but uses an an [ESM-Wrapper](https://redfin.engineering/node-modules-at-war-why-commonjs-and-es-modules-cant-get-along-9617135eeca1):
https://github.com/schnittstabil/merge-options/blob/a46b98f7a7c548f404d8c1c5c75d705501067839/package.json#L19-L23
