### ISSUE TITLE
cjs/esm support breaks IntelliSense of VSCode

### ISSUE THREAD

**Issue by jakobrosenberg** [schnittstabil/merge-options#24]
from `index.js`
```javascript
module.exports = function (...options) {
```

from `index.d.ts`
```typescript
export default function (...options: any[]): any;
```

VSCode expects the function to exist at `default`, while in reality, there is no `default` export.
![image](https://user-images.githubusercontent.com/4153004/92468977-59ca1c80-f1d4-11ea-9ebe-2ead34ccbf91.png)

**Comment by schnittstabil** [comment]
LGTM in TS and JS with `import`:
![image](https://user-images.githubusercontent.com/6059032/92898814-95582700-f41e-11ea-9f52-63639c5529a6.png)

But breaks with `require`:
![image](https://user-images.githubusercontent.com/6059032/92899184-e10ad080-f41e-11ea-9301-3a5280473e7b.png)

This module uses an [ESM-Wrapper](https://redfin.engineering/node-modules-at-war-why-commonjs-and-es-modules-cant-get-along-9617135eeca1):
https://github.com/schnittstabil/merge-options/blob/a46b98f7a7c548f404d8c1c5c75d705501067839/package.json#L19-L23

Hence, VSCode does not seem to fully support the `main` and `exports` fields and takes the wrong `index.[m]js`. I do not think we can solve this issue in this module. But if you know how, you are welcome to create a PR.
