### ISSUE TITLE
Breaking in webpack when ignore node_modules

### ISSUE THREAD

**Issue by manatarms** [schnittstabil/merge-options#3]
Hey,

Thanks for the package. I noticed that your es6 in 1.0.0 is not transpiled down to es5. I would suggest using babel to output  a dist because most people (like me) ignore node_modules for the transpilation process. Ignoring node_modules helps speed up the build by orders of magnitude. 

Cheers!

**Comment by schnittstabil** [comment]
>  …because most people (like me) ignore node_modules for the transpilation process.

Mhm, why? It sounds to be an issue of your tools, or at least their configuration.

Following your reasoning, every single package–which _could_ be useful in some non-ES6 environment–should provide an ES5 version along with its ES6 version. And if we go one step further, package maintainers should also provide ES2017, ES2018, … versions–a maintenance nightmare for developers like me, who spend their spare time to OSS :sweat:

Fixing your issue within `merge-options` seems to be the wrong place, but maybe I have overlooked something.

**Comment by manatarms** [comment]
> should provide an ES5 version along with its ES6 version

This is not true. A babel preset is all you need to transpile your es6 down to es5.  
Since es6 isn't fully supported by webpack uglify it removes a large part of the user base that could be using your plugin, along with the fact that node 4 does not understand es6. I'm reporting this issue because we have a million line code base and transpiling `node_modules` would take exponentially longer. Till now we have not had any issues because all of the plugins (About 70000 deps) we've used provide babel transpiled code. It would take a few minutes at most to set up a babel transpilation process for this code base. I would be happy to PR if that could help you. 
Cheers!

**Comment by schnittstabil** [comment]
>> should provide an ES5 version along with its ES6 version

> This is not true. A babel preset is all you need to transpile your es6 down to es5.

Maybe I have understood you wrong:
1. If I don't have to introduce a `babel` dependency in `devDependencies`
2. and thus I do not have to maintain that dependency (e.g. keep track of version bumps, etc.) 
3. and I do not have to keep a `dist` folder in sync with the sources–especially in case of PRs etc.
4. and the `git` history of this projects keeps simple and the diffs keep concise

well, then, I would be happy to manage that babel preset, but only as long as `babel` and `webpack` are leading–probably only for the next 2-5 years…

Do not get me wrong, I take your issue serious. But, please try to understand: I believe, this would introduce a lot of **maintenance work**.

**Comment by manatarms** [comment]
I understand your concerns and they are valid. I just wanted to make sure you knew about the issue we had. I appreciate your detailed answers.
I'm closing this issue but feel free to reopen it if you'd like me to make a PR for babel.

**Comment by schnittstabil** [comment]
> removes a large part of the user base that could be using your plugin, along with the fact that node 4 does not understand es6

Btw, `merge-options` works fine in node4 (https://travis-ci.org/schnittstabil/merge-options/builds/229371961)

> I'm reporting this issue because we have a million line code base and transpiling `node_modules` would take exponentially longer.

A _million line code base_ in one project? Personally, I would try to [_separate my concerns_](https://en.wikipedia.org/wiki/Separation_of_concerns) into distinct sub-projects. Beside the architectural benefits (e.g. benefits which come with [Design by contract](https://en.wikipedia.org/wiki/Design_by_contract) etc.), this probably reduces the need of transpiling the whole code base every time–just a suggestion.

As you probably use VCS to manage your code anyway, you can also fork `merge-options` (e.g. to your company-owned git server) and traspiling it in exactly the way you need it for your big project, see the [`package.json` documentation](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies) for details–I cannot guess which transpiled versions my consumers _really_ need.

**Comment by manatarms** [comment]
Sorry for the delayed response.

What I meant by a million line code base is that all our deps and dev deps together make up a million line code base. Which is why we try to improve our DX by excluding `node_modules` from the transpilation process. We were using this plugin in Fela, which we implement in our Cloudflare front end cf-ui code base here https://github.com/cloudflare/cf-ui.

Even though you may not know which versions are required by your consumers, the lib code should at least exclude non standard es6 features from the output. Babel is very easy to set up with next to no maintenance required.

**Comment by schnittstabil** [comment]
> Which is why we try to improve our DX by excluding `node_modules` from the transpilation process. We were using this plugin in Fela, which we implement in our Cloudflare front end cf-ui code base here https://github.com/cloudflare/cf-ui.

Sorry, I do not know what "DX" means and I do not know which package we are talking about–is it [`flea`](https://yarnpkg.com/en/package/flea) (which uses ES6 Template literals) or `cf-ui`? If it's `flea`, may you share a link to its source? https://github.com/fleajs/flea does not exists. Btw, both do not (directly) depend on `merge-options`! :confused: 

Anyway, I rethought your idea and I want to note that [`merge-options`](https://github.com/schnittstabil/merge-options/blob/d562042c9195160731f9ad77bd122f8a3991caa4/package.json#L20-L22) (and its dependency [is-plain-obj]([](https://github.com/sindresorhus/is-plain-obj/blob/d84e668e87037d5d04263ed4cfbfd91d9f01dd3d/package.json#L18-L20))) already minimize the transpiling overhead, via their [`files` `package.json` sections](https://docs.npmjs.com/files/package.json#files):
```json
  "files": [
    "index.js"
  ],
```

---

>[…], the lib code should at least exclude non standard es6 features from the output

The term "es6" refers to the [Standard ECMA-262 – ECMAScript® 2015 Language Specification](http://www.ecma-international.org/ecma-262/6.0/), which is obviously a _standard_; thus, I'm a bit puzzled–what ES6 features bothers you?

> Babel is very easy to set up with next to no maintenance required.

If it is so easy and you still think it is worth, please create a PR, thus I could better estimate the maintenance efforts.

**Comment by manatarms** [comment]
Sorry for the confusion. DX stands for developer experience. So the longer webpack takes to create the build, the worse the developer experience.

This is the package I was referring to [Fela](https://github.com/rofrischmann/fela). I believe we removed `merge-options` as a dependency recently. This is where we had to replace `merge-options` in cf-ui https://github.com/cloudflare/cf-ui/pull/270.

I completely agree with you that we should be used to write modern es6 code. The main problem here is that [uglifyjs-webpack-plugin](https://github.com/webpack-contrib/uglifyjs-webpack-plugin) is still using an [older](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/package.json#L34) UglifyJsPlugin version. The PR is tracked [here](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/63). Hopefully it'll get merged soon. Since a lot of people use webpack, your plugin has a chance of breaking on those builds.

I would be more than happy to make a PR, if you think it's worth it.

**Comment by WillsonHaw** [comment]
Just wanted to mention that I also have the same issue. I'm currently locking the version to 0.0.64 because I'm not going to add extra complexity and build time to webpack for transpiling to es5. We need es5 functionality because we need to support IE11.
