### ISSUE TITLE
Fails to build on create-react-app: Publish ES5 to NPM

### ISSUE THREAD

**Issue by glcheetham** [schnittstabil/merge-options#4]
When building a project using merge-options on create-react-app, `react-scripts build` will give the following error:
```
> react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

 	./node_modules/merge-options/index.js:11

Read more here: http://bit.ly/2tRViJ9
```

[This link](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify) to the create-react-app documentation explains the problem in more detail:

> Some third-party packages don't compile their code to ES5 before publishing to npm. This often causes problems in the ecosystem because neither browsers (except for most modern versions) nor some tools currently support all ES6 features. We recommend to publish code on npm as ES5 at least for a few more years.

**Comment by glcheetham** [comment]
See my PR  #5

**Comment by kisenka** [comment]
@schnittstabil could you please take a look at #5. I am really need it.

**Comment by glcheetham** [comment]
@kisenka you can use my fork instead https://www.npmjs.com/package/merge-options-es5

`npm i merge-options-es5`

**Comment by schnittstabil** [comment]
Sorry, I target node.js, if users want to use my modules in legacy browsers, it's up to them to transpile them. More importantly, those users know better which features they have to transpile than I do.

Btw, `create-react-app` extensively uses ES6+ features via Babel/Webpack, but is still unable to deal with (mature) ES6 features in dependencies. Trying to put the blame on maintainers of **node.js packages** is quite bizarre in my opinion.

Anyway, @glcheetham thanks for publishing your fork at npm. See also https://github.com/facebookincubator/create-react-app/issues/1125 for more workarounds.

**Comment by gaearon** [comment]
FYI, we're starting the work to compile deps with `babel-preset-env` in Create React App: https://github.com/facebookincubator/create-react-app/pull/3776

Let us know if you have feedback about how this should work.

**Comment by robatron** [comment]
@kisenka , @glcheetham , it's a bit hacky, but we just run an inline `babel` build on `merge-options` in our `postinstall` script:

*package.json*
```json
"postinstall": 
  "babel node_modules/merge-options/index.js -o node_modules/merge-options/index.js"
```

*.babelrc*
```json
{
  "presets": ["env"]
}
```
