### ISSUE TITLE
[production build] Unexpected token: operator (>) [scripts/main_d82bc1a8.js:7487,44]

### ISSUE THREAD

**Issue by strarsis** [schnittstabil/merge-options#6]
```js
import mergeOptions from 'merge-options';

mergeOption({}, {...}, arguments[0]);
````

Builds well with dev webpack build, but fails with webpack production build:
````
Unexpected token: operator (>) [scripts/main_d82bc1a8.js:7487,44]
````

**Comment by schnittstabil** [comment]
That seems to be an issue with your code or your webpack setup, not `merge-options`.
Furthermore, nobody could help you without knowing the contents of `scripts/main_d82bc1a8.js`.
