### ISSUE TITLE
Consideration for Alternate Array Handling

### ISSUE THREAD

**Issue by shellscape** [schnittstabil/merge-options#9]
I'd like to propose a method to handle array values differently. It's something that I find lacking in every single merge/deep-copy/extend/assign library I can find; none of them provide a means to concat array values rather than simple overriding them. 

It could be possible to create a _factory_ pattern that accepted options for determining behavior. e.g.

```js
const merge = mergeOptions.set({ arrays: 'concat' });
const result = merge({}, {a:[3]}, {a:[1,2]});
// { a: [3, 1, 2] }
```

That could support multiple different methods (which could even be user-extendible), with the default being the current behavior of right-most replacement as an object value.

**Comment by schnittstabil** [comment]
Mhm, doesn't [`concatArrays`](https://github.com/schnittstabil/merge-options#configconcatarrays) work for you?

```js
const result = mergeOptions.call({concatArrays: true}, {}, {a:[3]}, {a:[1,2]});
// { a: [3, 1, 2] }
```

> That could support multiple different methods (which could even be user-extendible), with the default being the current behavior of right-most replacement as an object value.

Can you elaborate this and give some examples? Maybe you are on the track of something.

**Comment by shellscape** [comment]
@schnittstabil man, I completely missed that option, thanks for pointing it out.

So in scenarios where options need to be passed to a method that typically operates on all `...args`, it's typically easier on users and sanity checking to provide a factory method which accepts only an options argument and returns an instance of the method which is scope-configured according to the options passed to the factory. In that way, `mergeOptions.set({ concatArray: true })` would return an instance of `mergeOptions` which could then be called such like `mergeOptions(obj1, obj2, ...)` without having to remember to have the first object be an options object. It also provides reuse of that configured instance without having to manually wrap `mergeOptions`.

**Comment by schnittstabil** [comment]
If I understand you correctly, you can already accomplish that via [Function.prototype.bind()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind):
```js
const mergeOptions = require('merge-options');

const merge = mergeOptions.bind({concatArrays: true})
merge({}, {a:[3]}, {a:[1,2]});
// { a: [ 3, 1, 2 ] }
```
